# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffmantic < Formula
  desc "Structural, semantic diff engine powered by Tree-sitter"
  homepage "https://github.com/HarshK97/diffmantic"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HarshK97/diffmantic/releases/download/v0.8.0/diffmantic_0.8.0_darwin_amd64.tar.gz"
      sha256 "cfc6c2550b8594a195a0dde3aa23d5d6e72eaa184777fa4b2d20138c7d0fbcc5"

      define_method(:install) do
        bin.install "diffm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HarshK97/diffmantic/releases/download/v0.8.0/diffmantic_0.8.0_darwin_arm64.tar.gz"
      sha256 "2d0bd2ff511b2adb77db87d37ab6d9377fd64440fd3fa6d9fe21c0a769434e50"

      define_method(:install) do
        bin.install "diffm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HarshK97/diffmantic/releases/download/v0.8.0/diffmantic_0.8.0_linux_amd64.tar.gz"
      sha256 "e3d6bdcc934405da7b706773f0c1af387b9b8f2f4e4ddaa5c940988b838b15df"
      define_method(:install) do
        bin.install "diffm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HarshK97/diffmantic/releases/download/v0.8.0/diffmantic_0.8.0_linux_arm64.tar.gz"
      sha256 "f0efecdd20b02b455c0644aee62e737e27fc7049acffbfe3e40cc6af447fdd75"
      define_method(:install) do
        bin.install "diffm"
      end
    end
  end

  test do
    system "#{bin}/diffm --version"
  end
end
